<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOJu7TuW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOJu7TuW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOJu7TuW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOJu7TuW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOJu7TuW\App_KernelDevDebugContainer([
    'container.build_hash' => 'OJu7TuW',
    'container.build_id' => '7440c757',
    'container.build_time' => 1718726147,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOJu7TuW');
