<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVZCt8hC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVZCt8hC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVZCt8hC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVZCt8hC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVZCt8hC\App_KernelDevDebugContainer([
    'container.build_hash' => 'VZCt8hC',
    'container.build_id' => 'ae0f76ec',
    'container.build_time' => 1748755588,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVZCt8hC');
